DROP TABLE  IF EXISTS STUDENT;
CREATE TABLE STUDENT(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(30),
    EMAIL VARCHAR(30) 
);

INSERT INTO STUDENT(NAME,EMAIL) VALUES('DIEM','DIEM@GMAIL.COM');